[package]
name = "axum_tutorial"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
axum = "0.8.7"
config = "0.15.19"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sqlite = "0.37.0"
tokio = { version = "1.48.0" , features = ["full"] }
